GET https://localhost:5001/test/index
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IkNJY0JmUkphbU1VQ0phbWRqc1VHN2ciLCJ0eXAiOiJhdCtqd3QifQ.eyJuYmYiOjE1OTE2NzIwOTcsImV4cCI6MTU5MTY3MzUzNywiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NTAwMSIsImF1ZCI6ImVnb3ZfYXBpcyIsImNsaWVudF9pZCI6IjQxOTI0NmY4LTZjYzYtNDMyNC04N2QyLTYzZWNlMTliOWVlNiIsInNjb3BlIjpbImVnb3ZfYXBpcyJdfQ.MWKSjXia5FdW6Vr2xvB6nsRlglWf7RjSr3AwQBDt0I7KwRGDIP9ipEku53BYWLssJshKpLUijqM9rPnYbbmoUPCHxQKQ6V6zP9wt3aHNgNr-g0bTd14ZSsEq7fuWT2N9mvLWvhf2Rlv-19Lp665q-tliB95fC1gmIqiQspo9s17-4YFwtL0lHD3qoU_py0tc7zL8YJs0gTRLDq9zNAaUkUqdoy9aK4jpAdMe0atFtNRwWbCq6iEshZcz6Er1npDERgPcjZX3ZETwraH8ZV_0AQE2d0kF_DmKcdRMB5F8IvPdM9skvGV8O8us9ZyL9OKkLVVrxIf-vgZ3z3I6MjvcuA
Accept: application/json

###
POST https://localhost:5001/connect/token
Content-Type: application/x-www-form-urlencoded

client_id=b80029e8-8a9d-47eb-b58d-13afd9b3bbc9&client_secret=2c425c74-466f-43e7-bcf1-2e8bde9371c4&grant_type=client_credentials

###

